language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
#  - hhvm

before_script:
  - git clone --recursive https://github.com/EnviMVC/EnviMVC3PHP.git Envi
  - mkdir ./tmp

script:
  - git --version
  - echo $LANG
  - export LANG=ja_JP.UTF-8
  - echo $LANG
  - ./Envi/envi unittest-go ./test.yml > ./tmp/test.log
  - echo $LANG
  - export LANG=en_US.UTF-8
  - echo $LANG
  - php ./test/status.php ./tmp/test.log

after_script:

notifications:
  slack:
    rooms:
      secure: your_token_key
