language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - git clone --recursive https://github.com/EnviMVC/EnviMVC3PHP.git Envi
  - mkdir ./tmp

script:
  - ,/Envi/envi unittest-go ./test.yml

after_script:

notifications:
  slack:
    rooms:
      secure: your_token_key
